# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
