# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_boy_girl'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Boy')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Girl')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
